### ISSUE TITLE
Enter on the overrider will update the symbol

### ISSUE THREAD

**Issue by vjandrei** [mwhite05/Button-Symbols#4]
Great job for this plugin. 
Some UX fix for the users. One is that if you write some thing on the Label override and hit enter will
tricker the cmd-j shortcut. This will be handy.
Second is the can the position-y and position-x be dropdowns? Se there is left-center-right-bottom-top selectors. 

👍🏻

**Comment by mwhite05** [comment]
Hi @vjandrei

Thank you. I'm glad you're finding this plugin useful!

I really wanted to make it so that pressing return or tabbing out of the field would immediately trigger the plugin without using cmd + j. However, Sketch has a broken system for responding to such events and they have essentially ignored my questions and issue reports.

In this section at the bottom of my Readme page there are a few links to the Sketch issues affecting further enhancement of this plugin: https://github.com/mwhite05/Button-Symbols#sketch-issues-causing-problems-for-the-growth-of-this-plugin

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

For the x and y position question; initially I did consider that but two primary things lead me to decide against it.

1) The x and y position system I developed is more robust than just top/left/bottom/right/center values. You can enter positive numeric values to give pixel offsets from the top or left and you can use negative values to offset from the bottom or right edges. You can also use a comma separated list of numeric offsets like 20,40. If that were used for the Position-X value you would end up with 20 pixels of space to the left and 40 pixels to the right of your button. You can see full details on all of the available options for all override values: https://github.com/mwhite05/Button-Symbols#what-do-the-overrides-do

2) The programming would be far more involved than what it took to develop the current version of this plugin.

**Comment by mwhite05** [comment]
@vjandrei 

Unfortunately there are no events I have found to tap into the symbol override field changing. I'm working on alternate solutions but have not come up with anything workable short of rewriting the entire plugin in native code (vs JavaScript) which is not something on the roadmap at this time. I'm going to continue experimenting and searching for a way to automatically trigger the update when the overrides change but as of now I'm considering this unlikely unless the Sketch API adds an event for it.

**Comment by vjandrei** [comment]
@mwhite05 Thanks for the reply. I will follow the evolution of this plugin 👍 
Good work.
